spring:
  application:
    name: fornecedor
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/fornecedordb
    username: root
    password: root 
